import { Component, CUSTOM_ELEMENTS_SCHEMA, OnDestroy, OnInit } from '@angular/core';
import { SignalServiceService } from '../../services/signal-service.service';

@Component({
  selector: 'app-youth',
  standalone: true,
  imports: [],
  templateUrl: './youth.component.html',
  styleUrl: './youth.component.less',
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class YouthComponent implements OnInit {

  constructor(private signal: SignalServiceService) { }
  ngOnInit(): void {
    this.signal.setHeader('Youth')
  }

  slide = [
    "../../../../assets/youth/header/slide1.jpg",
    "../../../../assets/youth/header/slide2.jpg",
    "../../../../assets/youth/header/slide3.jpg",
    "../../../../assets/youth/header/slide4.jpg",
    "../../../../assets/youth/header/slide5.jpg",
  ];

  content = [
    "../../../../assets/youth/content/content1.jpg",
    "../../../../assets/youth/content/content2.jpg",
    "../../../../assets/youth/content/content3.jpg",
    "../../../../assets/youth/content/content4.jpg",
    "../../../../assets/youth/content/content5.jpg",
    "../../../../assets/youth/content/content6.jpg",
    "../../../../assets/youth/content/content7.jpg",
    "../../../../assets/youth/content/content8.jpg",
    "../../../../assets/youth/content/content9.jpg",
    "../../../../assets/youth/content/content10.jpg",
    "../../../../assets/youth/content/content11.jpg",
    "../../../../assets/youth/content/content12.jpg",
    "../../../../assets/youth/content/content13.jpg",
    "../../../../assets/youth/content/content14.jpg",
    "../../../../assets/youth/content/content15.jpg",
    "../../../../assets/youth/content/content16.jpg",
    "../../../../assets/youth/content/content17.jpg",
    "../../../../assets/youth/content/content18.jpg",
    "../../../../assets/youth/content/content19.jpg",
    "../../../../assets/youth/content/content20.jpg",
    "../../../../assets/youth/content/content21.jpg",
    "../../../../assets/youth/content/content22.jpg",
    "../../../../assets/youth/content/content23.jpg",
    "../../../../assets/youth/content/content24.jpg",
    "../../../../assets/youth/content/content25.jpg",
    "../../../../assets/youth/content/content26.jpg",
    "../../../../assets/youth/content/content27.jpg",
    "../../../../assets/youth/content/content28.jpg",
    "../../../../assets/youth/content/content29.jpg",
    "../../../../assets/youth/content/content30.jpg",
    "../../../../assets/youth/content/content31.jpg",
    "../../../../assets/youth/content/content32.jpg",
    "../../../../assets/youth/content/content33.jpg",
    "../../../../assets/youth/content/content34.jpg",
    "../../../../assets/youth/content/content35.jpg",
    "../../../../assets/youth/content/content36.jpg",
    "../../../../assets/youth/content/content37.jpg",
    "../../../../assets/youth/content/content38.jpg",
    "../../../../assets/youth/content/content39.jpg",
    "../../../../assets/youth/content/content40.jpg",
    "../../../../assets/youth/content/content41.jpg",
    "../../../../assets/youth/content/content42.jpg",
    "../../../../assets/youth/content/content43.jpg",
    "../../../../assets/youth/content/content44.jpg",
    "../../../../assets/youth/content/content45.jpg",
    "../../../../assets/youth/content/content46.jpg",
    "../../../../assets/youth/content/content47.jpg",
    "../../../../assets/youth/content/content48.jpg",
    "../../../../assets/youth/content/content49.jpg",
    "../../../../assets/youth/content/content50.jpg",
    "../../../../assets/youth/content/content51.jpg",
    "../../../../assets/youth/content/content52.jpg",
    "../../../../assets/youth/content/content53.jpg",
    "../../../../assets/youth/content/content54.jpg",
    "../../../../assets/youth/content/content55.jpg",
    "../../../../assets/youth/content/content56.jpg",
    "../../../../assets/youth/content/content57.jpg",
    "../../../../assets/youth/content/content58.jpg",
    "../../../../assets/youth/content/content59.jpg",
    "../../../../assets/youth/content/content60.jpg",
    "../../../../assets/youth/content/content61.jpg",
    "../../../../assets/youth/content/content62.jpg",
    "../../../../assets/youth/content/content63.jpg",
    "../../../../assets/youth/content/content64.jpg",
    "../../../../assets/youth/content/content65.jpg",
    "../../../../assets/youth/content/content66.jpg",
    "../../../../assets/youth/content/content67.jpg",
    "../../../../assets/youth/content/content68.jpg",
    "../../../../assets/youth/content/content69.jpg",
    "../../../../assets/youth/content/content70.jpg",
    "../../../../assets/youth/content/content71.jpg",
    "../../../../assets/youth/content/content72.jpg",
    "../../../../assets/youth/content/content73.jpg",
    "../../../../assets/youth/content/content74.jpg",
    "../../../../assets/youth/content/content75.jpg",
    "../../../../assets/youth/content/content76.jpg",
    "../../../../assets/youth/content/content77.jpg",
    "../../../../assets/youth/content/content78.jpg",
    "../../../../assets/youth/content/content79.jpg",
    "../../../../assets/youth/content/content80.jpg",
    "../../../../assets/youth/content/content81.jpg",
    "../../../../assets/youth/content/content82.jpg",
    "../../../../assets/youth/content/content83.jpg",
    "../../../../assets/youth/content/content84.jpg",
    "../../../../assets/youth/content/content85.jpg",
    "../../../../assets/youth/content/content86.jpg",
    "../../../../assets/youth/content/content87.jpg",
    "../../../../assets/youth/content/content88.jpg",
    "../../../../assets/youth/content/content89.jpg",
    "../../../../assets/youth/content/content90.jpg",
    "../../../../assets/youth/content/content91.jpg",
    "../../../../assets/youth/content/content92.jpg",
    "../../../../assets/youth/content/content93.jpg",
    "../../../../assets/youth/content/content94.jpg",
    "../../../../assets/youth/content/content95.jpg",
    "../../../../assets/youth/content/content96.jpg",
    "../../../../assets/youth/content/content97.jpg",
    "../../../../assets/youth/content/content98.jpg",
    "../../../../assets/youth/content/content99.jpg",
    "../../../../assets/youth/content/content100.jpg",
    "../../../../assets/youth/content/content101.jpg",
    "../../../../assets/youth/content/content102.jpg",
    "../../../../assets/youth/content/content103.jpg",
    "../../../../assets/youth/content/content104.jpg",
    "../../../../assets/youth/content/content105.jpg",
    "../../../../assets/youth/content/content106.jpg",
    "../../../../assets/youth/content/content107.jpg",
    "../../../../assets/youth/content/content108.jpg",
    "../../../../assets/youth/content/content109.jpg",
    "../../../../assets/youth/content/content110.jpg",
  ]
}
